/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: 3bd3218662632ec1c405b5eb1a134078)
interface __BaseEnv_Env {
	CONTENT: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	RL_ENUM: RateLimit;
	RL_UNLOCK: RateLimit;
	RL_OBSERVE: RateLimit;
	RL_SIGNAL: RateLimit;
	PUBLIC_BASE: string;
	ALERT_EMAIL_TO: string;
	ALERT_EMAIL_FROM: string;
	NZIP_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_BASE" | "ALERT_EMAIL_TO" | "ALERT_EMAIL_FROM" | "NZIP_TOKEN">> {}
}
