/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 990c104e67727cf0d631159dadc2a132)
interface __BaseEnv_Env {
	CONTENT: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	RL_ENUM: RateLimit;
	RL_UNLOCK: RateLimit;
	RL_OBSERVE: RateLimit;
	RL_SIGNAL: RateLimit;
	ALERT_EMAIL_TO: "operator@example.com";
	ALERT_EMAIL_FROM: "alerts@share.example.com";
	NZIP_TOKEN: string;
	PUBLIC_BASE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALERT_EMAIL_TO" | "ALERT_EMAIL_FROM" | "NZIP_TOKEN" | "PUBLIC_BASE">> {}
}
